# ワークフロー名
name: test_line_notify

# 実行タイミング
on:
 schedule:
   - cron: '53 23 * * *'

# 実行内容
jobs:
  build:
    # Ubuntsuで実行
    runs-on: ubuntu-latest
    
    # 実行する処理＆コマンド
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests
      - name: Run script
        env:
          LINE_NOTIFY_TOKEN: ${{secrets.LINE_NOTIFY_TOKEN}}
        run: |
          # main.pyの実行
          python main.py
